# Use the official Node.js 14 image as the base image
FROM node:22.1-bullseye

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Copy entrypoint script and wait-for-it script, ensure proper line endings
COPY .docker/docker-entrypoint.sh /docker-entrypoint.sh
COPY .docker/wait-for-it.sh /usr/src/app/.docker/wait-for-it.sh
RUN chmod +x /docker-entrypoint.sh && \
    chmod +x /usr/src/app/.docker/wait-for-it.sh && \
    sed -i 's/\r$//' /docker-entrypoint.sh && \
    sed -i 's/\r$//' /usr/src/app/.docker/wait-for-it.sh && \
    cat /docker-entrypoint.sh

# Install project dependencies
RUN npm install

# Copy the rest of the project files to the working directory
COPY . .

# Build the project
#RUN npm run build

# Expose a port (if your application needs it)
EXPOSE 3000

# Specify the environment variable
ENV CONTAINER_TYPE=worker

# Use custom entrypoint script
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD [ "npm", "run", "worker" ]