name: Build and Deploy

on:
  push:
    branches: [ "main" , "staging" ]

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to CCSO Docker Registry
      uses: docker/login-action@v3
      with:
        registry: registry.psuccso.org
        username: robot$ota+github
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Generate API Tag Names
      run: |
        echo "${{ steps.extract_branch.outputs.branch }}"
        if [ ${{ steps.extract_branch.outputs.branch }} = "main" ]; then
          echo "TAG_LATEST_API=ota-api:latest" >> $GITHUB_ENV
          echo "TAG_COMMIT_API=ota-api:$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        elif [ ${{ steps.extract_branch.outputs.branch }} = "staging" ]; then
          echo "TAG_LATEST_API=ota-api-stage:latest" >> $GITHUB_ENV
          echo "TAG_COMMIT_API=ota-api-stage:$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        else
          exit 0
        fi

    - name: Build and push API
      uses: docker/build-push-action@v6
      with:
        context: ./api
        platforms: linux/amd64,linux/arm64
        file: ./api/.docker/Dockerfile
        push: true
        tags: |
          registry.psuccso.org/ota/${{ env.TAG_LATEST_API }}
          registry.psuccso.org/ota/${{ env.TAG_COMMIT_API }}
        cache-from: type=registry,ref=registry.psuccso.org/ota/${{ env.TAG_LATEST_API }}
        cache-to: type=inline

  build-ui:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to CCSO Docker Registry
      uses: docker/login-action@v3
      with:
        registry: registry.psuccso.org
        username: robot$ota+github
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Generate UI Tag Names
      run: |
        echo "${{ steps.extract_branch.outputs.branch }}"
        if [ ${{ steps.extract_branch.outputs.branch }} = "main" ]; then
          echo "TAG_LATEST_UI=ota-ui:latest" >> $GITHUB_ENV
          echo "TAG_COMMIT_UI=ota-ui:$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        elif [ ${{ steps.extract_branch.outputs.branch }} = "staging" ]; then
          echo "TAG_LATEST_UI=ota-ui-stage:latest" >> $GITHUB_ENV
          echo "TAG_COMMIT_UI=ota-ui-stage:$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        else
          exit 0
        fi

    - name: Build and push UI
      uses: docker/build-push-action@v6
      with:
        context: ./vue
        platforms: linux/amd64,linux/arm64
        file: ./vue/.docker/Dockerfile
        push: true
        tags: |
          registry.psuccso.org/ota/${{ env.TAG_LATEST_UI }}
          registry.psuccso.org/ota/${{ env.TAG_COMMIT_UI }}
        cache-from: type=registry,ref=registry.psuccso.org/ota/${{ env.TAG_LATEST_UI }}
        cache-to: type=inline

  deploy-rancher:
    needs: [build-api, build-ui]
    runs-on: ubuntu-latest
    steps:
    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch

    - name: Redeploy Rancher
      run: |
        url='https://rancher.psuccso.com'
        cluster=local
        token=${{ secrets.RANCHER_TOKEN }}

        redeploy() {
            local app=$1
            pod_upgrade_body=$(curl -s -u "$token" \
            -k $url/k8s/clusters/$cluster/v1/apps.deployments/$namespace/$app \
            -X GET \
            -H 'Accept: application/json' \
            -H 'Content-Type: application/json' \
            -H 'Pragma: no-cache' \
            -H 'Cache-Control: no-cache' 2>&1 | sed  "s/\"cattle\.io\/timestamp\"\:\"[0-9T:Z-]*\"/\"cattle\.io\/timestamp\":\"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\"/g")

            curl -u "$token" \
            -k -s $url/k8s/clusters/$cluster/v1/apps.deployments/$namespace/$app \
            -X PUT \
            -H 'Accept: application/json' \
            -H 'Content-Type: application/json' \
            --data-binary "$pod_upgrade_body" --compressed
        }

        echo "${{ steps.extract_branch.outputs.branch }}"
        if [ ${{ steps.extract_branch.outputs.branch }} = "main" ]; then
            namespace=psuccso-ota
            redeploy "api"
            redeploy "vue"
        elif [ ${{ steps.extract_branch.outputs.branch }} = "staging" ]; then
            namespace=psuccso-ota-staging
            redeploy "api"
            redeploy "vue"
        else
            exit 0
        fi